### ISSUE TITLE
Can I see entire rqt_graph?

### ISSUE THREAD

**Issue by KimHyeJun1** [georgealexakis/factory_robot#1]
Hello. I'm University student in Korea.
I'm trying to use astra camera for autonomous navigated robot with QR detection.
So, astra camera driver and factory.launch works well individually.
Then, I have to connect astra to factory.launch, but I couldn't know how could do this. So, I want to see rqt_graph, which launched all of things for autonomous navigated robot with QR detection.

![rosgraph](https://github.com/georgealexakis/factory_robot/assets/109134044/18763bf9-c744-43f0-be95-4542a3e1dda4)

Above image is my rqt_graph, when launched astra camera driver and factory.launch

**Comment by georgealexakis** [comment]
You can just remap the camera topics in the launch file: [tracklive_kinect.launch](https://github.com/georgealexakis/factory_robot/blob/master/launch/tracklive_kinect.launch) and of course run the launch file of tyour camera or add it on the factory.launch.
